"""Compatibility facade for receipt-specific parser helpers.

New code should import from the focused receipt_* modules directly.
"""
# ruff: noqa: F401

import re
from collections import Counter
from difflib import SequenceMatcher
from itertools import combinations

from .schema import VALID_TAX_RATES, REDUCED_RATE, STANDARD_RATE

from .patterns import (
    ERA_TABLE,
    _ADMIN_FEE_DESCRIPTION_RE,
    _BAG_DESC_RE,
    _BANNER_PHRASE_RE,
    _COMPANY_SUFFIX_RE,
    _DECORATIVE_RE,
    _FOOD_DESC_RE,
    _FUEL_KEYWORDS,
    _GENERIC_DESC_MARKERS,
    _HEADER_LINE_RE,
    _HEADER_PHONE_MERCHANT_RE,
    _JUNK_DESC_RE,
    _OFFICIAL_AUTHORITY_HEADER_RE,
    _OFFICIAL_DEPARTMENT_LINE_RE,
    _QTY_DETAIL_DESC_RE,
    _SERVICE_FEE_DESCRIPTION_RE,
    _SERVICE_TAX_RATE_EVIDENCE_RE,
    _SKIP_PRICE_LINE,
    _has_service_inclusive_tax_evidence,
    _is_service_fee_description,
    era_to_western_year,
    should_override_field,
)

from .receipt_financial import (
    _STOP_BASIC,
    _STOP_FINANCIAL,
    _STOP_TAX,
    _TOTALS_VALUE_RE,
    _bare_number_tax_summary_entries,
    _collect_yen_values,
    _column_split_label_value_pairs,
    _extract_all_yen_nearby,
    _extract_financial_totals_impl,
    _extract_yen_max_nearby,
    _extract_yen_min_nearby,
    _extract_yen_nearby,
    _find_subset_sum,
    _inner_tax_target_amount_matches_total,
    _interleaved_rate_tax_summary_entries,
    _is_stacked_summary_padding_label,
    _is_tax_summary_stack_label,
    _parse_amount_fragment,
    _parse_yen_match,
    _text_says_displayed_prices_are_tax_included,
    extract_financial_totals,
    extract_points_used,
    extract_rate_bases,
    normalize_tax_label,
    normalize_tax_rate,
    reconcile_points_payment_from_ocr,
)

from .receipt_items import (
    _amount_from_yen_text,
    _bag_entries_from_ocr,
    _clean_admin_fee_description,
    _code_prefixed_ocr_desc_before,
    _drop_non_product_line_items,
    _fix_bag_description_from_ocr_code_context,
    _fix_bag_item_prices_from_ocr,
    _fix_bag_item_prices_from_rate_bases,
    _fix_bare_service_receipt_without_itemization,
    _fix_colon_split_product_names_from_ocr,
    _fix_duplicate_descriptions_from_ocr,
    _fix_item_desc_from_ocr_price_line,
    _fix_junk_descriptions,
    _fix_line_items,
    _fix_o_ring_descriptions_from_ocr,
    _fix_qty_code_row_descriptions_from_ocr,
    _fix_single_service_inclusive_tax,
    _fix_small_non_bag_item_prices_from_ocr,
    _fix_zero_prices_from_ocr,
    _money_line_value,
    _nontaxable_base_matches_total,
    _recover_discounted_item_from_gap,
    _recover_missing_bag_items_from_ocr,
    _recover_nontaxable_admin_fee_item,
    _recover_qty_unit_total_item_from_empty_extraction,
    _recover_repeated_item_from_gap,
    _replace_repeated_ocr_item_block_when_balanced,
    _replace_vertical_price_qty_total_rows_when_balanced,
)

from .receipt_phase_trace import (
    POSTPROCESS_MUTATION_FIELDS,
    POSTPROCESS_PHASES,
    POSTPROCESS_PHASE_BY_NAME,
    _diff_receipt_mutation_fields,
    _record_receipt_mutation,
    _record_receipt_phase_mutation,
    _snapshot_receipt_mutation_fields,
)

from .receipt_totals import (
    _canonical_subtotal_from_taxes,
    _drop_unprinted_small_target_only_taxes,
    _items_plus_tax_matches_total,
    _line_items_sum,
    _prefer_printed_item_sum_total_when_balanced,
    _restore_bare_number_tax_summary,
    _restore_external_tax_total_from_printed_subtotal,
    _restore_printed_summary_total_when_tax_balanced,
    _sum_taxable_amounts,
)

from .receipt_identity_payment import (
    _BUSINESS_HOURS_RE,
    _DATE_LINE_RE,
    _TIME_HHMM_RE,
    _TIME_JP_RE,
    _apply_financial_overrides,
    _clean_merchant_candidate,
    _fix_company_name_merchant,
    _fix_date,
    _fix_payment_method,
    _fix_time,
    _fix_toll_payment_reference,
    _fix_total_from_stacked_cash_tender_block,
    _fix_unlabeled_cash_tender_change_block,
    _merchant_looks_invalid,
    _official_authority_header_candidate,
    _parse_time_from_segment,
)

from .receipt_projection import (
    _OCR_QTY_NOTATION_RE,
    _OCR_TRAILING_PRICE_RE,
    _OCR_ZONE_END_RE,
    _clean_ocr_price_line_desc,
    _clear_discount_when_negative_line_precedes_own_price,
    _find_ocr_item_desc,
    _fix_item_totals_from_ocr_neighborhood,
    _group_layout_rows,
    _layout_block_center_y,
    _layout_block_height,
    _layout_price_value,
    _layout_qty_detail_total,
    _layout_row_price_candidates,
    _merge_qty_detail_into_previous,
    _norm_layout_desc,
    _parse_qty_detail_total,
    _project_totals_to_layout_rows,
    _project_totals_to_ocr_multiset,
    _repair_column_split_items,
    _repair_previous_item_from_following_qty_detail,
    _replace_hallucinated_dup_with_ocr_item,
)

from .receipt_item_repair import (
    _PRE_PRICE_STACK_METADATA_RE,
    _apply_qty_notation_from_ocr,
    _clean_code_prefixed_item_descriptions,
    _dedup_same_total_items,
    _drop_banner_phantom_items,
    _drop_duplicate_with_embedded_price,
    _drop_phantom_from_tax_amount,
    _expand_collapsed_items,
    _extract_fuel_usage,
    _find_discounted_ocr_item_desc,
    _fix_code_table_descriptions_by_order,
    _fix_digit_misread_items,
    _fix_fuel_item_description,
    _fix_fuel_volume_qty,
    _fix_priced_in_name_items,
    _fix_qty_from_ocr_patterns,
    _fix_qty_hallucinations,
    _fix_single_item_qty_from_ocr,
    _fix_single_service_item_from_ocr,
    _fix_split_item_price_body_total_layout,
    _insert_item_by_ocr_order,
    _ocr_line_index_for_item,
    _qty_detail_owner_indices,
    _remove_unit_rate_phantom_items,
    _replace_duplicate_desc_from_ocr,
    _revert_unsupported_qty_inflation,
    _strip_embedded_price_in_desc,
    _valid_ocr_item_desc,
    _valid_pre_price_stack_item_desc,
)

from .receipt_tax_categories import (
    _apply_single_bag_standard_rate_split,
    _assign_single_standard_rate_from_small_base,
    _assign_visible_bags_to_standard_rate,
    _fix_nonfood_packaging_tax_categories,
    _fix_tax_categories_from_ocr_markers,
    _fix_tax_categories_from_price_line_markers,
    _is_bag_description,
    _rebalance_standard_categories_from_reduced_rate_markers,
    _rebalance_tax_categories_to_rate_bases,
    _refine_rate_bases_from_tax_amounts,
    assign_tax_categories,
    reconcile_tax_categories_from_rate_bases,
)

from .receipt_row_projection import (
    _append_missing_low_value_bag_from_gap,
    _fix_numeric_desc_from_ocr_price_context,
    _fix_qty_context_and_reduced_rate_from_ocr,
    _replace_barcode_qty_price_rows_when_balanced,
    _replace_barcode_unit_qty_amount_stack_when_balanced,
    _replace_dense_item_rows_when_balanced,
    _replace_dense_sequence_rows_when_balanced,
    _replace_item_price_qty_rows_when_balanced,
    _replace_overage_item_with_low_value_bag,
    _replace_service_table_items_when_balanced,
)

from .receipt_marker_projection import (
    _fix_qty_totals_from_ocr_unit_lines,
    _replace_campaign_discount_stream_when_balanced,
    _replace_jan_pos_items_when_balanced,
    _replace_prefixed_tax_marker_item_rows_when_balanced,
)

from .receipt_item_cleanup import (
    _clear_discounts_without_nearby_ocr_marker,
    _detect_ocr_discounts,
    _drop_duplicate_rows_when_subtotal_balances,
    _ensure_discounted_ocr_pairs_present,
    _fill_single_qty_unit_prices_from_totals,
    _fix_adjacent_ocr_price_shift_when_balanced,
    _fix_discount_totals,
    _fix_discounted_item_gross_prices_from_ocr,
    _fix_embedded_price_suffix_totals,
    _fix_hallucinated_prices,
    _fix_misattributed_discounts,
    _fix_non_bag_items_named_as_bag,
    _normalize_taxes,
    _repair_discounted_line_item_totals_when_balanced,
    _repair_discounted_ocr_pair_descriptions,
    _repair_pre_price_stack_descriptions_from_ocr,
    _repair_rate_discounts_from_ocr_amounts,
    _replace_basket_marker_rows_when_balanced,
)

from .receipt_recovery import (
    _apply_coupon_discount_blocks,
    _drop_applied_coupon_line_items,
    _fix_implausible_tax_amounts,
    _fix_item_totals_from_following_discount_lines,
    _fix_items_from_subtotal,
    _fix_printed_tax_amounts_from_structural_blocks,
    _printed_inclusive_tax_blocks,
    _recover_missing_items_from_gap,
    _recover_multiple_missing_items_from_gap,
    _repair_tiny_item_prices_from_following_ocr,
    _replace_split_price_block_when_balanced,
    _restore_explicit_tax_rate_amount_lines,
    _restore_printed_external_tax_amounts,
)

from .receipt_late_repairs import (
    _drop_numeric_marker_description_rows,
    _fix_header_store_line_location,
    _fix_name_bag_amount_shift_from_ocr,
    _fix_small_bag_description_from_ocr_entry,
    _fix_split_address_location_from_ocr,
    _fix_split_bag_price_from_nearby_single_digit,
    _recover_labeled_purchase_site_location,
    _replace_stacked_name_price_rows_when_balanced,
    _restore_single_rate_inclusive_tax_block,
    _restore_stacked_inclusive_tax_block,
    _restore_tax_excluded_per_rate_blocks,
    _restore_zero_points_when_no_redemption,
)

from .receipt_postprocess_phases import (
    _run_adjacent_price_shift_reconciliation_phase,
    _run_bag_amount_shift_reconciliation_phase,
    _run_bag_item_ocr_repair_phase,
    _run_bag_item_rate_base_reconciliation_phase,
    _run_barcode_row_projection_phase,
    _run_bare_number_tax_summary_restoration_phase,
    _run_basket_marker_rows_phase,
    _run_body_total_layout_reconstruction_phase,
    _run_campaign_discount_projection_phase,
    _run_cash_tender_reconciliation_phase,
    _run_code_prefixed_description_cleanup_phase,
    _run_coupon_discount_projection_phase,
    _run_dense_item_row_projection_phase,
    _run_dense_sequence_row_projection_phase,
    _run_digit_misread_item_repair_phase,
    _run_discount_consistency_reconciliation_phase,
    _run_discounted_ocr_item_repair_phase,
    _run_duplicate_row_cleanup_phase,
    _run_explicit_tax_amount_restoration_phase,
    _run_external_tax_total_restoration_phase,
    _run_financial_totals_repair_phase,
    _run_following_ocr_price_projection_phase,
    _run_gap_item_recovery_phase,
    _run_header_location_repair_phase,
    _run_implausible_tax_amount_repair_phase,
    _run_item_name_price_cleanup_phase,
    _run_jan_pos_row_projection_phase,
    _run_line_item_cleanup_phase,
    _run_low_value_bag_recovery_phase,
    _run_merchant_identity_repair_phase,
    _run_ocr_description_reconciliation_phase,
    _run_payment_method_repair_phase,
    _run_payment_points_reconciliation_phase,
    _run_phantom_tax_amount_cleanup_phase,
    _run_prefixed_tax_marker_item_rows_phase,
    _run_priced_name_item_repair_phase,
    _run_printed_external_tax_amount_restoration_phase,
    _run_printed_item_sum_total_repair_phase,
    _run_printed_summary_total_tax_repair_phase,
    _run_quantity_detail_reconciliation_phase,
    _run_service_receipt_recovery_phase,
    _run_single_item_quantity_repair_phase,
    _run_single_rate_inclusive_tax_restoration_phase,
    _run_small_target_only_tax_pruning_phase,
    _run_split_price_block_projection_phase,
    _run_stacked_inclusive_tax_restoration_phase,
    _run_stacked_name_price_projection_phase,
    _run_subtotal_item_price_repair_phase,
    _run_tax_category_assignment_phase,
    _run_tax_excluded_rate_block_restoration_phase,
    _run_toll_payment_reference_repair_phase,
    _run_transaction_datetime_repair_phase,
    _run_vertical_price_qty_total_projection_phase,
    _tax_assignment_rate_bases,
)

from .receipt_postprocess import (
    postprocess_receipt,
)
